# -*- mode: ruby -*-
# vi: set ft=ruby :

NUM_WORKERS = 1

Vagrant.configure('2') do |config|
  config.vm.define 'head' do |head|
    head.vm.box = 'centos/7'
    head.vm.hostname = 'head'

    head.vm.network 'private_network', ip: '192.168.205.10'

    head.vm.provider 'virtualbox' do |vb|
      vb.memory = '8192'
      vb.cpus = 2
    end

    head.vm.provision :shell, path: 'bootstrap.sh'
  end

  (1..NUM_WORKERS).each do |n|
    config.vm.define "worker#{n}" do |worker|
      worker.vm.box = 'centos/7'
      worker.vm.hostname = "worker#{n}"

      worker.vm.network 'private_network', ip: "192.168.205.1#{n}"

      worker.vm.provider 'virtualbox' do |vb|
        vb.memory = '8192'
      end
      worker.vm.provision :shell, path: 'bootstrap.sh'
    end
  end
end
