# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Set up base box as centos/7. Most be at least version 7
  # to use Docker.
  config.vm.box = "centos/7"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 9117, host: 9117

  # Virtualbox provider-specific configuration
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     # vb.gui = true

     # Customize the amount of memory on the VM:
     vb.name = "prometheus-httpd"
     vb.memory = "8192"
  end

  # Provision with bootstrap.sh
  config.vm.provision :shell, :path => "bootstrap.sh"
end
